In [81]:
import cv2
import os
import pandas as pd
from tqdm import tqdm

In [77]:
dataset = os.path.join('D:/Latihan/Combined')
dataset

'D:/Latihan/Combined'

In [80]:
filenames = []
folder = []
image = []
shape = []
x = []
y = []

for path, subdirs, files in tqdm(os.walk(dataset)):
    for name in files:
        filenames += [os.path.join(path, name)]
        folder += [os.path.basename(os.path.dirname(filenames[-1]))]
        image += [os.path.basename(filenames[-1])]
        
for i in range (len(filenames)) :
    shape += [cv2.imread(filenames[i]).shape[0:2]]

for i in range (len(filenames)) :
    x += [shape[i][0]]
    y += [shape[i][1]]

1it [00:00, ?it/s]

In [79]:
print("Ukuran gambar dalam dataset memiliki nilai minimum untuk (x,y) yaitu x={} dan y{}".format(min(x),min(y)))

Ukuran gambar dalam dataset memiliki nilai minimum untuk (x,y) yaitu x=210 dan y318

In [87]:
data = pd.DataFrame({'Image path':filenames, 'Class':folder, 'Name_Image':image,
                    'Shape(x,y)':shape, 'x':x, 'y':y})
data.sort_values(by=['x','y'])

                    Image path     Class Name_Image    Shape(x,y)     x     y
2   D:/Latihan/Combined\11.jpg  Combined     11.jpg    (210, 318)   210   318
11   D:/Latihan/Combined\2.jpg  Combined      2.jpg    (360, 640)   360   640
15   D:/Latihan/Combined\5.jpg  Combined      5.jpg    (366, 650)   366   650
16   D:/Latihan/Combined\6.jpg  Combined      6.jpg    (400, 600)   400   600
6   D:/Latihan/Combined\15.jpg  Combined     15.jpg    (415, 739)   415   739
19   D:/Latihan/Combined\9.jpg  Combined      9.jpg    (421, 746)   421   746
12  D:/Latihan/Combined\20.jpg  Combined     20.jpg    (466, 658)   466   658
5   D:/Latihan/Combined\14.jpg  Combined     14.jpg    (486, 698)   486   698
18   D:/Latihan/Combined\8.jpg  Combined      8.jpg    (500, 800)   500   800
1   D:/Latihan/Combined\10.jpg  Combined     10.jpg    (565, 848)   565   848
3   D:/Latihan/Combined\12.jpg  Combined     12.jpg    (642, 700)   642   700
17   D:/Latihan/Combined\7.jpg  Combined      7.jpg   (667, 1000)   667  1000
14   D:/Latihan/Combined\4.jpg  Combined      4.jpg   (763, 1024)   763  1024
4   D:/Latihan/Combined\13.jpg  Combined     13.jpg   (764, 1024)   764  1024
7   D:/Latihan/Combined\16.jpg  Combined     16.jpg   (768, 1280)   768  1280
10  D:/Latihan/Combined\19.jpg  Combined     19.jpg   (853, 1280)   853  1280
13   D:/Latihan/Combined\3.jpg  Combined      3.jpg   (900, 1200)   900  1200
9   D:/Latihan/Combined\18.jpg  Combined     18.jpg    (933, 700)   933   700
0    D:/Latihan/Combined\1.jpg  Combined      1.jpg  (1200, 1200)  1200  1200
8   D:/Latihan/Combined\17.jpg  Combined     17.jpg  (1200, 1200)  1200  1200